
import os
import glob
import socket

if 'raijin' in socket.gethostname():
    f90 = 'ifort'
else:
    f90 = 'gfortran'

flags = ['-i4', '-r8']

# Expects netcdf and mpi headers to be in the standard include path. 
env = Environment(ENV=os.environ, F90=f90, LINK=f90, F90FLAGS=' '.join(flags), LINKFLAGS=' '.join(flags))

sources = glob.glob('*.F90')
# Filter out the .mod to build libraries.
objs = [o for o in env.Object(sources) if o.get_suffix() == '.o']

env.Library('libauscom', objs)
