#!/bin/ksh
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Set environment variables required in container & job config
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export RUNID=aiihc
export RUN_ON=hpc1c-r00
export USERID=frrh

export UM_SVN_URL=svn://fcm2/UM_svn/UM/trunk
export UM_SVN_BIND=$UM_SVN_URL/src/configs/bindings
export UM_CONTAINER=$UM_SVN_BIND/container.cfg

export UM_MAINDIR=$LOCALDATA/$RUNID
export UM_RMAINDIR=/data/cr/ocean/$USERID/$RUNID
export UM_RHOST=hpc1c-r00
export UM_OUTDIR=$LOCALDATA/$RUNID
export UM_ROUTDIR=/data/cr/ocean/$USERID/$RUNID
export UM_MACHINE=ibm-pwr6-meto

export UM_USR_MACH_OVRDS=/dev/null
export UM_USR_FILE_OVRDS=/dev/null

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Create extract directories
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if test ! -d $UM_OUTDIR/umbase; then
   echo "Creating directory $UM_OUTDIR/umbase"
   mkdir -p $UM_OUTDIR/umbase
fi

# For UM model and Reconfiguration 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if test ! -d $UM_OUTDIR/ummodel; then
   echo "Creating directory $UM_OUTDIR/ummodel"
   mkdir -p $UM_OUTDIR/ummodel
fi


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Create fcm extract statement(s)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# For UM model and Reconfiguration 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Base extract: 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export UM_OUTDIR=$UM_MAINDIR/umbase
export UM_ROUTDIR=$UM_RMAINDIR/umbase
export UM_JOB_CFG=/home/h03/haddj/umui_jobs/$RUNID/FCM_UMUI_BASE_CFG
fcm extract  -v 3 $UM_SVN_BIND/container.cfg@vn7.3 1> $UM_OUTDIR/ext.out 2>&1

RC=$?
if test $RC -eq 0 ; then 
    echo Base extract:  OK
else
    echo Base extract:  failed
    exit $RC 
fi

# Set overrides files properly before model or reconf extract
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export UM_USR_MACH_OVRDS=/home/h03/haddj/umui_jobs/$RUNID/USR_MACH_OVRDS
export UM_USR_FILE_OVRDS=/home/h03/haddj/umui_jobs/$RUNID/USR_FILE_OVRDS

# Model extract: 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export UM_OUTDIR=$UM_MAINDIR/ummodel
export UM_ROUTDIR=$UM_RMAINDIR/ummodel
export UM_JOB_CFG=/home/h03/haddj/umui_jobs/$RUNID/FCM_UMUI_MODEL_CFG
fcm extract  -v 3 $UM_SVN_BIND/container.cfg@vn7.3 1> $UM_OUTDIR/ext.out 2>&1

RC=$?
if test $RC -eq 0 ; then 
    echo Model extract:  OK
else
    echo Model extract:  failed
    exit $RC 
fi

# For NEMO and CICE 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
if test ! -d $UM_MAINDIR/um_nemo_cice; then 
echo "Creating directory $UM_MAINDIR/um_nemo_cice" 
mkdir -p $UM_MAINDIR/um_nemo_cice
fi

# NEMO-CICE extract: 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export UM_MAINDIR=$UM_MAINDIR/um_nemo_cice
fcm extract  -v 3 /home/h03/haddj/umui_jobs/$RUNID/FCM_NEMOCICE_CFG 1> $UM_MAINDIR/ext.out 2>&1

RC=$?
if test $RC -eq 0 ; then 
    echo NEMO-CICE extract:  OK
else
    echo NEMO-CICE extract:  failed
    exit $RC 
fi

