#!/usr/bin/ksh
#---------------------------------------------------------------------
# Script: fcm_main
#---------------------------------------------------------------------
#
# Purpose: Calls fcm extract on a local machine and fcm build
#          and/or run commands on a remote machine
#
# Created from umui vn7.3
#---------------------------------------------------------------------


#---------------------------------------------------------------------
#   Exported variables
#---------------------------------------------------------------------

export RUNID=aiihc
export RUN_ON=hpc1c-r00
export USERID=frrh
export UM_RDATADIR=$DATADIR/$RUNID

export UM_SVN_URL=svn://fcm2/UM_svn/UM/trunk
export UM_SVN_BIND=$UM_SVN_URL/src/configs/bindings
export UM_CONTAINER=$UM_SVN_BIND/container.cfg

#---------------------------------------------------------------------
# For this job follow actions will be performed:
#   DO_CLR=0  Do nothing
#   DO_CLR=1  Build Only
#   DO_CLR=2  Run Only
#   DO_CLR=3  Build and Run
#---------------------------------------------------------------------

DO_EXTR=true
DO_CLR=3
export RC=0

#---------------------------------------------------------------------
#   Extract commands
#---------------------------------------------------------------------

if test $DO_EXTR = "true" -a  $RC -eq 0 ; then
   echo
   echo FCM_MAIN: Calling Extract ...
/home/h03/haddj/umui_jobs/aiihc/FCM_EXTR_SCR
   RC=$?
   if test $RC -eq 0 ; then
     echo FCM_MAIN: Extract OK
   else
     echo FCM_MAIN: Extract failed >&2
     echo Tidying up directories ...
     ssh -q ${RUN_ON} -l ${USERID} -n "rm -rf ~/umui_runs/$RUNID-$1"
     echo FCM_MAIN stopped with return code $RC
     exit
   fi
 fi

#---------------------------------------------------------------------
#   Generated remote script
#---------------------------------------------------------------------

RUN_FILE=umuisubmit_clr

#---------------------------------------------------------------------
#   Submit to compile or/and run
#---------------------------------------------------------------------

 if test $RC -eq 0 ; then
   echo
   echo FCM_MAIN: Submitting $RUN_FILE ...
          /home/h03/haddj/umui_jobs/aiihc/UMSUBMIT -h $RUN_ON -u ${USERID} ${RUNID} ${RUN_FILE}
   RC=$?
   if test $RC -eq 0 ; then
     echo FCM_MAIN: Submit OK
   else
     echo FCM_MAIN: Submit failed >&2
   fi
 fi
 
exit 0

#EOF
