
import os
env = Environment(ENV={'PATH' : os.environ['PATH']}, F90='ifort', F90FLAGS='-i4 -r8 -I/apps/netcdf/4.2.1.1/include/Intel/', LIBS='netcdff')
sources = ['save_field_mod.F90']
env.Library('myflib', sources)
